model:
  type: inf-llm
  path: openbmb/MiniCPM-2B-sft-bf16
  block_size: 128
  n_init: 128
  n_local: 2048
  topk: 16
  repr_topk: 4
  max_cached_block: 32
  exc_block_size: 512
  fattn: false
  base: 10000
  distance_scale: 1.0

max_len: 2147483647
chunk_size: 8192
conv_type: minicpm
